version: '3.1'

services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      POSTGRES_USER: lis
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ~/db/data:/var/lib/postgresql/data
